#!/usr/bin/env python3
# -*- coding: utf-8 -*-

se=[]

def dna2rna(DNA:str):
    return(DNA.translate(str.maketrans("AGCT","UCGA")))

def dna_compl(dna:str) -> str:
    return(dna[::-1].translate(str.maketrans("AGCT", "TCGA")))

def pp_calc_sub(dna:str) -> int:
    global se
    ends=["UAG","UAA","UGA"]
    begins=["AUG"]
    reading = False
    counter = 0
    rna=dna2rna(dna)
    idx=0
    se=[]
    se_tmp=[None,None]
    for i in range(len(dna)-2):
        curr3=rna[i:i+3]
        if reading:
            idx+=1
            if idx%3!=0:
                continue
            if ends.count(curr3):
                counter=counter+1
                reading=False
                se_tmp[1]=i+3
                se.append(se_tmp.copy())
                idx=0
        else:
            if begins.count(curr3):
                reading=True
                se_tmp[0]=i
    return(counter)

def print_se(dna:str):
    global se
    i=0
    for se_tmp in se:
        i+=1
        print("No. "+str(i)+": "+str(se_tmp[0])+"-->"+str(se_tmp[1])+", len: "+ str(((se_tmp[1]-se_tmp[0]))//3))
        print(dna[se_tmp[0]:se_tmp[1]])

def pp_calc(dna:str):
    '''
    Compute the number of polypeptides produced by any user-specified DNA sequence.
    :param dna:
    :return:
    '''
    print("Input DNA get "+str(pp_calc_sub(dna))+" polypipetides.")
    print_se(dna)
    print("Completemeentary DNA get "+str(pp_calc_sub(dna_compl(dna)))+" polypipetides.")
    print_se(dna_compl(dna))

pp_calc("""ATGTTGAATAGTTCAAGAAAATATGCTTGTCGTTCCCTATTCAGACAAGCGAACGTCTCAATAAAAGGACTCTTTTATAATGGAGGCGCATATCGAAGAGGGTTTTCAACGGGATGTTGTTTGAGGAGTGATAACAAGGAAAGCCCAAGTGCAAGACAACCACTAGATAGGCTACAACTAGGTGATGAAATCAATGAACCAGAGCCTATTAGAACCAGGTTTTTTCAATTTTCCAGATGGAAGGCCACCATTGCTCTATTGTTGCTAAGTGGTGGGACGTATGCCTATTTATCAAGAAAAAGACGCTTGCTAGAAACTGAAAAGGAAGCAGATGCTAACAGAGCTTACGGTTCAGTAGCACTTGGCGGTCCTTTCAATTTAACAGATTTTAATGGTAAGCCTTTCACTGAGGAGAATTTGAAGGGTAAGTTTTCCATTTTATACTTTGGATTCAGTCATTGCCCCGACATTTGTCCAGAAGAGCTTGACAGATTAACGTATTGGATTTCTGAATTAGATGATAAAGACCATATAAAGATACAGCCATTGTTTATCTCATGTGATCCTGCAAGAGATACACCGGATGTCTTGAAAGAGTACTTAAGCGATTTTCACCCAGCTATCATTGGTTTAACCGGTACGTACGACCAAGTGAAAAGCGTATGCAAAAAATACAAGGTATATTTTTCAACTCCACGTGATGTCAAGCCCAACCAGGATTACTTAGTGGACCATTCGATATTTTTCTATTTGATCGACCCTGAAGGACAGTTTATCGATGCGTTGGGAAGAAACTACGATGAGCAATCTGGTCTCGAAAAGATTCGTGAACAAATTCAGGCGTATGTGCCAAAGGAAGAACGGGAGCGTAGGTCAAAAAAATGGTACTCTTTTATCTTC""")
# Input DNA get 7 polypipetides.
# No. 1: 172-->289, len: 39
# TACAACTAGGTGATGAAATCAATGAACCAGAGCCTATTAGAACCAGGTTTTTTCAATTTTCCAGATGGAAGGCCACCATTGCTCTATTGTTGCTAAGTGGTGGGACGTATGCCTATT
# No. 2: 345-->408, len: 21
# TACGGTTCAGTAGCACTTGGCGGTCCTTTCAATTTAACAGATTTTAATGGTAAGCCTTTCACT
# No. 3: 441-->471, len: 10
# TACTTTGGATTCAGTCATTGCCCCGACATT
# No. 4: 538-->565, len: 9
# TACAGCCATTGTTTATCTCATGTGATC
# No. 5: 575-->743, len: 56
# TACACCGGATGTCTTGAAAGAGTACTTAAGCGATTTTCACCCAGCTATCATTGGTTTAACCGGTACGTACGACCAAGTGAAAAGCGTATGCAAAAAATACAAGGTATATTTTTCAACTCCACGTGATGTCAAGCCCAACCAGGATTACTTAGTGGACCATTCGATATT
# No. 6: 795-->825, len: 10
# TACGATGAGCAATCTGGTCTCGAAAAGATT
# No. 7: 885-->897, len: 4
# TACTCTTTTATC
# Completemeentary DNA get 5 polypipetides.
# No. 1: 13-->67, len: 18
# TACCATTTTTTTGACCTACGCTCCCGTTCTTCCTTTGGCACATACGCCTGAATT
# No. 2: 219-->294, len: 25
# TACCTTGTATTTTTTGCATACGCTTTTCACTTGGTCGTACGTACCGGTTAAACCAATGATAGCTGGGTGAAAATC
# No. 3: 301-->364, len: 21
# TACTCTTTCAAGACATCCGGTGTATCTCTTGCAGGATCACATGAGATAAACAATGGCTGTATC
# No. 4: 400-->547, len: 49
# TACGTTAATCTGTCAAGCTCTTCTGGACAAATGTCGGGGCAATGACTGAATCCAAAGTATAAAATGGAAAACTTACCCTTCAAATTCTCCTCAGTGAAAGGCTTACCATTAAAATCTGTTAAATTGAAAGGACCGCCAAGTGCTACT
# No. 5: 619-->712, len: 31
# TACGTCCCACCACTTAGCAACAATAGAGCAATGGTGGCCTTCCATCTGGAAAATTGAAAAAACCTGGTTCTAATAGGCTCTGGTTCATTGATT
